// src/components/BackToTop.tsx
'use client';
import { useState, useEffect } from 'react';
import { ChevronUp } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import styles from './BackToTop.module.css';

export default function BackToTop() {
    const [isVisible, setIsVisible] = useState(false);

    useEffect(() => {
        const toggleVisibility = () => {
            if (window.pageYOffset > 500) {
                setIsVisible(true);
            } else {
                setIsVisible(false);
            }
        };

        window.addEventListener('scroll', toggleVisibility);
        return () => window.removeEventListener('scroll', toggleVisibility);
    }, []);

    const scrollToTop = () => {
        window.scrollTo({
            top: 0,
            behavior: 'smooth',
        });
    };

    return (
        <AnimatePresence>
            {isVisible && (
                <motion.button
                    initial={{ opacity: 0, scale: 0.5 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.5 }}
                    onClick={scrollToTop}
                    className={styles.button}
                    aria-label="Back to Top"
                >
                    <ChevronUp size={24} />
                </motion.button>
            )}
        </AnimatePresence>
    );
}

// app/components/BackToTop.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from "vue"
import { ChevronUp } from "lucide-vue-next"
import styles from "./BackToTop.module.css"

const isVisible = ref(false)

function toggleVisibility() {
  isVisible.value = window.scrollY > 500
}

function scrollToTop() {
  window.scrollTo({ top: 0, behavior: "smooth" })
}

onMounted(() => window.addEventListener("scroll", toggleVisibility))
onBeforeUnmount(() => window.removeEventListener("scroll", toggleVisibility))
</script>

<template>
  <AnimatePresence>
    <Motion v-if="isVisible" as="button" :initial="{ opacity: 0, scale: 0.5 }" :animate="{ opacity: 1, scale: 1 }"
      :exit="{ opacity: 0, scale: 0.5 }" :class="styles.button" aria-label="Back to Top" @click="scrollToTop">
      <ChevronUp :size="24" />
    </Motion>
  </AnimatePresence>
</template>
